# Лабораторная работа. Проведение разведочного анализа

В этом задании вы сможете попрактиковаться в некоторых концепциях и навыках по обработке данных с помощью библиотеки Pandas.

Просматривая этот блокнот, вы найдете **???** в определенных местах. Для выполнения этого задания необходимо заменить все **???** с соответствующими значениями, выражениями или операторами, чтобы обеспечить правильную сквозное выполнение блокнота.

Некоторые вещи, которые следует иметь в виду:
- Обязательно запустите все ячейки кода, иначе вы можете получить ошибки, например, NameError для неопределенных переменных.
- Не изменяйте имена переменных, не удаляйте ячейки и не нарушайте другой существующий код. Это может вызвать проблемы во время оценки.
- В некоторых случаях вам может понадобиться добавить некоторые ячейки кода или новые операторы до или после строки кода, содержащей ???.
- Вопросы, отмеченные (необязательно), не будут рассматриваться для оценки и могут быть пропущены. Они для вашего обучения.

## Как запустить код и сохранить свою работу

Рекомендуемый способ запуска этой записной книжки — выбрать пункт меню «Среда выполнения» (если вы работаете в Google Colab) и нажать "Выполнить все".

In [ ]:
# Run the next line to install Pandas
!pip install pandas --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.4)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
import pandas as pd

В этом задании мы собираемся проанализировать работу с данными из файла CSV. Начнем с загрузки CSV-файла. Файл размещен в репозитории https://github.com/SerjiEvg/data-analysis/raw/main/data/countries.csv.

In [ ]:
countries_df = pd.read_csv('https://github.com/SerjiEvg/data-analysis/raw/main/data/countries.csv')

countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775

### **Задание 1. Сколько стран содержит фрейм данных?**

*Подсказка:* используйте метод .shape.

In [ ]:
num_countries = ???

In [ ]:
print('There are {} countries in the dataset'.format(num_countries))

### **Задание 2. Получить список континентов из фрейма данных?**

*Подсказка:* используйте метод ряда .unique.

In [ ]:
continents = ???

In [ ]:
continents

### **Задание 3. Какова общая численность населения всех стран, перечисленных в этом наборе данных?**

In [ ]:
total_population = ???

In [ ]:
print('Численность населения равна {}.'.format(int(total_population)))

##### **Вопрос. (необязательно) Какова общая продолжительность жизни в мире?**

*Подсказка:* вам нужно взять средневзвешенную ожидаемую продолжительность жизни, используя население в качестве весов.

### **Задание 4. Создайте фрейм данных, содержащий 10 стран с наибольшим населением.**

*Подсказка:* свяжите методы sort_values и .head

In [ ]:
most_populous_df = ???

In [ ]:
most_populous_df

### **Задание 5. Добавьте новый столбец countries_df для записи общего ВВП по стране (произведение населения и ВВП на душу населения).**

In [ ]:
countries_df['gdp'] = ???

In [ ]:
countries_df

##### **Вопрос. (Необязательно) Создайте фрейм данных, содержащий 10 стран с самым низким ВВП на душу населения среди округов с населением более 100 миллионов человек.**

## **Задание 6. Создать фрейм данных, содержащий количество стран на каждом континенте?**

**Подсказка:** используйте groupby, выберите  столбец location и агрегируйте с помощью count.

In [ ]:
country_counts_df = ???

In [ ]:
country_counts_df

## **Задание 7. Создайте фрейм данных, показывающий общую численность населения каждого континента.**

*Подсказка:* используйте groupby, выберите столбец совокупности и агрегируйте, используя sum.

In [ ]:
continent_populations_df = ???

In [ ]:
continent_populations_df

Давайте загрузим еще один CSV-файл, содержащий общую статистику Covid-19 для разных стран, и прочитаем данные в другой фрейм данных Pandas.

In [ ]:
covid_data_df = pd.read_csv('https://github.com/SerjiEvg/data-analysis/raw/main/data/covid-countries-data.csv')

In [ ]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

### **Задание 8. Подсчитайте количество стран, по которым  отсутствуют данные total_tests.**

*Подсказка:* используйте метод .isna.

In [ ]:
total_tests_missing = ???

In [ ]:
print("Данные по общему количеству тестов отсутствуют для {} стран.".format(int(total_tests_missing)))

Давайте объединим два фрейма данных и вычислим еще несколько показателей.

### **Задание 9. Объединить countries_df с covid_data_df в столбце location.**

*Подсказка:* используйте .merge метод на countries_df

In [ ]:
combined_df = ???

In [ ]:
combined_df

### **Задание 10. Добавьте столбцы tests_per_million и cases_per_million в deaths_per_million combined_df**

In [ ]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [ ]:
combined_df['cases_per_million'] = ???

In [ ]:
combined_df['deaths_per_million'] = ???

In [ ]:
combined_df

### **Задание 11. Создайте фреймворк данных с 10 странами с наибольшим количеством тестов на миллион человек.**

In [ ]:
highest_tests_df = ???

In [ ]:
highest_tests_df

### **Задание 12. Создайте фрейм данных с 10 странами с наибольшим количеством положительных случаев на миллион человек.**

In [ ]:
highest_cases_df = ???

In [ ]:
highest_cases_df

### **Задание 13. Создайте фрейм данных с 10 странами с наибольшим числом смертей на миллион человек?**

In [ ]:
highest_deaths_df = ???

In [ ]:
highest_deaths_df

### **Задание 14. (Необязательно) Подсчитайте количество стран, которые фигурируют в обоих списках «наибольшее количество тестов на миллион» и «наибольшее количество случаев на миллион».**

### **Задание 15. (Необязательно) Подсчитайте количество стран, которые входят в оба списка «20 стран с самым низким ВВП на душу населения» и «20 стран с самым низким количеством больничных коек на тысячу населения». При создании списка учитывайте только страны с населением более 10 миллионов человек.**

## **Сохранение и отправка**

Если вы работаете с сервисом Google Colab, то в меню "Файл" выберите пункт "Скачать" в формате .IPYNB. Это ваша версия блокнота. Загрузите блокнот как ответ на задание.