# Лабораторная работа №5. Введение в разведочный анализ с Pandas

В этом задании вы сможете попрактиковаться в некоторых концепциях и навыках по обработке данных с помощью библиотеки Pandas.

Просматривая этот блокнот, вы найдете **???** в определенных местах. Для выполнения этого задания необходимо заменить все **???** с соответствующими значениями, выражениями или операторами, чтобы обеспечить правильную сквозное выполнение блокнота.

Некоторые вещи, которые следует иметь в виду:
- Обязательно запустите все ячейки кода, иначе вы можете получить ошибки, например, NameError для неопределенных переменных.
- Не изменяйте имена переменных, не удаляйте ячейки и не нарушайте другой существующий код. Это может вызвать проблемы во время оценки.
- В некоторых случаях вам может понадобиться добавить некоторые ячейки кода или новые операторы до или после строки кода, содержащей ???.
- Вопросы, отмеченные (необязательно), не будут рассматриваться для оценки и могут быть пропущены. Они для вашего обучения.

## Как запустить код и сохранить свою работу

Рекомендуемый способ запуска этой записной книжки — выбрать пункт меню «Среда выполнения» (если вы работаете в Google Colab) и нажать "Выполнить все".

In [ ]:
# Run the next line to install Pandas
!pip install pandas --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
import pandas as pd

В этом задании мы собираемся проанализировать работу с данными из файла CSV. Начнем с загрузки CSV-файла. Файл размещен в репозитории https://github.com/SerjiEvg/data-analysis/raw/main/data/grades.csv.

In [ ]:
df = ???

df

### **Задание 1. Изучение набора данных?**

Чтобы понять набор данных, введите с помощью команд Pandas: a) head, б) tail, c) dtypes, д) info, е) describe

In [ ]:
#a) (1)

In [ ]:
#б) (1)

In [ ]:
#c) (1)

In [ ]:
#д) (1)

In [ ]:
#e) (1)

### **Задание 2. Очистка набора данных**

a) Используйте приведенный ниже метод clean_currency, чтобы удалить запятые и знаки денежной единицы из столбца «Сбережения» (Руб.) и поместить их в новый столбец под названием «Сбережения».

In [ ]:
def clean_currency(curr):
    return float(curr.replace(",", "").replace("руб.", ""))

clean_currency("66,000 руб.")

66000.0

In [ ]:
# Избавьтесь от руб. и , в столбце Сбережения, чтобы конвертировать в формат float

б) Выведите grades.dtypes.Сбережения, чтобы проверить, произошло ли изменение типа.

In [ ]:
#б)

с) Запустите 'grades["Пол"].value_counts()', чтобы увидеть неправильные поля «М», которые необходимо преобразовать в «Муж.».

In [ ]:
# с)

д) Теперь используйте «.str.replace» в столбце «Пол», чтобы скрыть неправильные поля «M». Подсказка: мы должны использовать ^...$, чтобы ограничить шаблон соответствием всей строке.

In [ ]:
# д)


df["Пол"].value_counts()

In [ ]:
df

е) Однако это не относится к установленному столбцу выпускников ["Пол"]. Вам нужно будет обновить столбец при использовании команды замены 'alumni["Gender"]= ', покажите, как это делается ниже

In [ ]:
# е) (1)

ж) Вы можете установить его напрямую с помощью команды df.loc, покажите, как это можно сделать с помощью команды «df.loc[row_indexer,col_indexer] = value» для преобразования «M» в «Мужской».

In [ ]:
# ж) (1)

з) Теперь снова запустите «value_counts» для пола, чтобы увидеть правильные столбцы — «Мужской» и «Женский».

In [ ]:
# з) (1)

### **Задание 3. Анализ данных**

a) получить медиану, б) вычислить среднее c) выяислить стандартное отклонение для столбца 'Зарплата'

In [ ]:
# a)(1)

In [ ]:
# b)(1)

In [ ]:
# c)(1)

д) определить, какие выпускники заплатили более 15000 руб., используя столбец «Платеж».

In [ ]:
# д) (1)

### **Задание 4. Визуализация данных**

a) Используя столбец «Тип диплома», постройте столбчатую диаграмму и покажите количество ее значений.

In [ ]:
#a) (1)

б) Создайте прямоугольную диаграмму для сравнения столбцов "Зарплата" и "Сбережения"

In [ ]:
#b) (1)

c) Создайте гистограмму со столбцом «Зарплата», используя 12 интервалов.

In [ ]:
#c) (1)

д) Создайте точечный график, сравнивая столбцы «Зарплата» и «Сбережения».

In [ ]:
#d) (1)

## **Сохранение и отправка**

Если вы работаете с сервисом Google Colab, то в меню "Файл" выберите пункт "Скачать" в формате .IPYNB. Это ваша версия блокнота. Загрузите блокнот как ответ на задание.